In [40]:
import tensorflow as tf

In [41]:
print(tf.__version__)

1.3.0


In [42]:
hello = tf.constant("Hello ")

In [43]:
world = tf.constant("World")

In [44]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [45]:
print(hello)

Tensor("Const_5:0", shape=(), dtype=string)


In [46]:
with tf.Session() as sess:  #this with command make sure that we do not have to close the session manually
    result =sess.run(hello+world)
    

In [47]:
print(result)    #this b is a bytes literal

b'Hello World'


# addition

In [48]:
a = tf.constant(10)

In [49]:
b = tf.constant(20)

In [50]:
type(a)

tensorflow.python.framework.ops.Tensor

In [51]:
a+b

<tf.Tensor 'add_8:0' shape=() dtype=int32>

In [52]:
a+b

<tf.Tensor 'add_9:0' shape=() dtype=int32>

In [53]:
with tf.Session() as sess:
    result= sess.run(a+b)

In [54]:
result

30

In [55]:
const = tf.constant(10)

In [56]:
fill_mat = tf.fill((4,4),10)

In [57]:
myzeros = tf.zeros((4,4))

In [58]:
myones= tf.ones((4,4))

In [59]:
myrandn = tf.random_normal((4,4), mean=0, stddev=1.0)

In [60]:
myrandu = tf.random_uniform((4,4), minval= 0, maxval=1)

# interactive sesssion example

In [61]:
my_ops = [const, fill_mat, myzeros,myones,myrandn,myrandu]

In [62]:
sess = tf.InteractiveSession()         #only useful for notebook settings

In [63]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[-0.24090549  0.61183929 -0.28171191  0.35044533]
 [-2.36980438 -0.87355876 -0.07645231 -0.82937217]
 [-0.40950015 -3.50856924 -0.04256503  0.5720278 ]
 [ 0.34690949  1.02446938  2.42614722 -0.22067058]]


[[ 0.55521441  0.3124907   0.08584368  0.81001222]
 [ 0.3310715   0.71527243  0.32076001  0.78169489]
 [ 0.79320884  0.39565611  0.73195434  0.17892277]
 [ 0.78014708  0.85595906  0.69370663  0.62952769]]




.EVAL MODE

In [65]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[ 0.98481196  1.09136665 -1.56711245  0.1549527 ]
 [ 0.50577301  0.25839573 -2.06428242 -2.29914093]
 [ 0.6037603  -0.47020566  0.63979119  0.74357545]
 [ 0.15865041 -0.63071543 -0.33777648  2.21867466]]


[[ 0.79658711  0.3341924   0.24717259  0.88906538]
 [ 0.01793015  0.61888254  0.00849426  0.35084915]
 [ 0.77964795  0.26315355  0.84341025  0.86158037]
 [ 0.65882182  0.87654603  0.9034549   0.8954047 ]]




In [66]:
a = tf.constant([[1,2],[3,4]])

In [67]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [68]:
b = tf.constant([[10],[100]])

In [69]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [70]:
result = tf.matmul(a,b)

In [71]:
sess.run(result)

array([[210],
       [430]])

In [72]:
result.eval()

array([[210],
       [430]])